version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}

  mongo:
    image: mongo:6
    container_name: nestjs-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
